import factory
from django.contrib.auth import get_user_model
from factory.django import DjangoModelFactory

from soroscan.ingest.models import (
    ContractABI,
    ContractEvent,
    ContractMetadata,
    EventSchema,
    RemediationIncident,
    RemediationRule,
    TrackedContract,
    WebhookDeliveryLog,
    WebhookSubscription,
)

User = get_user_model()


class UserFactory(DjangoModelFactory):
    class Meta:
        model = User

    username = factory.Sequence(lambda n: f"user{n}")
    email = factory.Sequence(lambda n: f"user{n}@example.com")


class TrackedContractFactory(DjangoModelFactory):
    class Meta:
        model = TrackedContract

    # Encode the sequence counter into the Base32-safe alphabet (A-Z, 2-7) so
    # every factory-generated ID satisfies the TrackedContract.contract_id
    # RegexValidator (^C[A-Z2-7]{55}$).  Digits 0, 1, 8, 9 are not valid
    # Base32 characters and were previously generated by zfill(55).
    contract_id = factory.Sequence(
        lambda n: (
            "C"
            + (
                lambda val: (
                    "".join(
                        "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567"[val >> (5 * i) & 0x1F]
                        for i in range(54, -1, -1)
                    )
                )
            )(n % (32 ** 55))
        )
    )
    name = factory.Sequence(lambda n: f"Contract {n}")
    description = "Test contract"
    owner = factory.SubFactory(UserFactory)
    is_active = True
    network = TrackedContract.Network.MAINNET
    deprecation_status = TrackedContract.DeprecationStatus.ACTIVE
    deprecation_reason = ""
    event_filter_type = TrackedContract.FILTER_NONE
    event_filter_list = factory.LazyFunction(list)


class EventSchemaFactory(DjangoModelFactory):
    class Meta:
        model = EventSchema

    contract = factory.SubFactory(TrackedContractFactory)
    version = 1
    event_type = "test_event"
    json_schema = {
        "type": "object",
        "properties": {"amount": {"type": "number"}},
        "required": ["amount"],
    }


class ContractEventFactory(DjangoModelFactory):
    class Meta:
        model = ContractEvent

    contract = factory.SubFactory(TrackedContractFactory)
    event_type = "swap"
    payload = {"amount": 100, "from": "Alice", "to": "Bob"}
    payload_hash = factory.Sequence(lambda n: f"{'a' * 64}")
    ledger = factory.Sequence(lambda n: 1000 + n)
    event_index = factory.Sequence(lambda n: n)
    timestamp = factory.Faker("date_time")
    tx_hash = factory.Sequence(lambda n: f"{'b' * 64}")


class WebhookSubscriptionFactory(DjangoModelFactory):
    class Meta:
        model = WebhookSubscription

    contract = factory.SubFactory(TrackedContractFactory)
    event_type = "swap"
    target_url = "https://example.com/webhook"
    secret = factory.Sequence(lambda n: f"secret_{n}")
    is_active = True
    status = WebhookSubscription.STATUS_ACTIVE


class WebhookDeliveryLogFactory(DjangoModelFactory):
    class Meta:
        model = WebhookDeliveryLog

    subscription = factory.SubFactory(WebhookSubscriptionFactory)
    event = factory.SubFactory(ContractEventFactory)
    attempt_number = 1
    status_code = 200
    success = True
    error = ""


class ContractABIFactory(DjangoModelFactory):
    class Meta:
        model = ContractABI

    contract = factory.SubFactory(TrackedContractFactory)
    abi_json = [
        {
            "name": "transfer",
            "fields": [
                {"name": "from", "type": "Address"},
                {"name": "to", "type": "Address"},
                {"name": "amount", "type": "I128"},
            ],
        }
    ]


class RemediationRuleFactory(DjangoModelFactory):
    class Meta:
        model = RemediationRule

    name = factory.Sequence(lambda n: f"Remediation Rule {n}")
    condition = factory.LazyAttribute(
        lambda o: {
            "type": "no_events_for_minutes",
            "contract_id": f"C{'A' * 55}",
            "minutes": 60,
        }
    )
    actions = [{"type": "pause_contract"}]
    enabled = True
    grace_period_minutes = 10
    alert_type = RemediationRule.ALERT_SLACK
    alert_target = "https://example.com/remediation-alert"
    dry_run = False


class RemediationIncidentFactory(DjangoModelFactory):
    class Meta:
        model = RemediationIncident

    rule = factory.SubFactory(RemediationRuleFactory)
    contract = factory.SubFactory(TrackedContractFactory)
    status = RemediationIncident.STATUS_ALERTED
    anomaly_snapshot = {"type": "no_events_for_minutes", "minutes": 60}


class ContractMetadataFactory(DjangoModelFactory):
    class Meta:
        model = ContractMetadata

    contract = factory.SubFactory(TrackedContractFactory)
    name = factory.Sequence(lambda n: f"Contract Metadata {n}")
    description = factory.Faker("paragraph")
    tags = factory.LazyFunction(list)
    documentation_url = ""
    github_repo = ""
    team_email = ""
