# Generated by Django
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import soroscan.ingest.models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0011_data_retention"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EncryptionKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.PositiveIntegerField(unique=True, help_text="Key version used for identifying which key encrypted the payload")),
                ("encrypted_key", models.BinaryField(help_text="AES-256-GCM key encrypted with the master key")),
                ("is_active", models.BooleanField(default=False, help_text="Is this the current key used for new encryptions?")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="KeyRotationLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(help_text="Action performed (e.g. Generated Initial, Rotated)", max_length=64)),
                ("key_version", models.PositiveIntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who initiated the rotation (null for automated)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AlterField(
            model_name="contractevent",
            name="decoded_payload",
            field=soroscan.ingest.models.EncryptedJSONField(blank=True, help_text="ABI-decoded event payload (human-readable fields), transparently encrypted", null=True),
        ),
    ]
