# Generated by Django 5.2.10 on 2026-03-24 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0011_data_retention'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=128)),
                ('object_type', models.CharField(max_length=32)),
                ('object_id', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0')),
                ('changes', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ContractSigningKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(choices=[('ed25519', 'Ed25519'), ('ecdsa', 'ECDSA')], default='ed25519', max_length=16)),
                ('public_key', models.TextField(help_text='Public key for signature verification (hex/base64/raw PEM)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contract Signing Key',
                'verbose_name_plural': 'Contract Signing Keys',
            },
        ),
        migrations.AddField(
            model_name='contractevent',
            name='signature_status',
            field=models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('missing', 'Missing')], db_index=True, default='missing', help_text='Result of event signature verification', max_length=16),
        ),
        migrations.AddIndex(
            model_name='contractevent',
            index=models.Index(fields=['signature_status'], name='ingest_cont_signatu_39e92a_idx'),
        ),
        migrations.AddField(
            model_name='adminaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractsigningkey',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signing_key', to='ingest.trackedcontract'),
        ),
        migrations.AddIndex(
            model_name='adminaction',
            index=models.Index(fields=['action', 'timestamp'], name='ingest_admi_action_cc906d_idx'),
        ),
        migrations.AddIndex(
            model_name='adminaction',
            index=models.Index(fields=['object_type', 'object_id'], name='ingest_admi_object__bb6a68_idx'),
        ),
    ]
