# Generated by Django 5.2.10 on 2026-03-24 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0012_adminaction_contractsigningkey_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemediationIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('alerted', 'Alerted'), ('executed', 'Executed'), ('resolved', 'Resolved')], default='alerted', max_length=16)),
                ('anomaly_snapshot', models.JSONField(default=dict)),
                ('first_detected_at', models.DateTimeField(auto_now_add=True)),
                ('alerted_at', models.DateTimeField(blank=True, null=True)),
                ('action_after_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-first_detected_at'],
            },
        ),
        migrations.CreateModel(
            name='RemediationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('condition', models.JSONField(help_text="Condition JSON, e.g. {'type': 'no_events_for_minutes', 'contract_id': 'C...', 'minutes': 60}")),
                ('actions', models.JSONField(default=list, help_text='List of action objects: pause_contract, send_alert, disable_webhooks')),
                ('enabled', models.BooleanField(default=True)),
                ('grace_period_minutes', models.PositiveIntegerField(default=10)),
                ('alert_type', models.CharField(choices=[('slack', 'Slack'), ('email', 'Email'), ('webhook', 'Webhook')], default='slack', max_length=16)),
                ('alert_target', models.TextField(blank=True, help_text='Ops destination (Slack webhook URL, email, or webhook URL)')),
                ('dry_run', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='remediationincident',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediation_incidents', to='ingest.trackedcontract'),
        ),
        migrations.AddField(
            model_name='remediationincident',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='ingest.remediationrule'),
        ),
        migrations.AddIndex(
            model_name='remediationincident',
            index=models.Index(fields=['rule', 'contract', 'status'], name='ingest_reme_rule_id_d51331_idx'),
        ),
        migrations.AddIndex(
            model_name='remediationincident',
            index=models.Index(fields=['action_after_at'], name='ingest_reme_action__a1a430_idx'),
        ),
    ]
