# Generated by Django 5.2.10 on 2026-03-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0017_eventdeduplicationlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alertexecution',
            new_name='ingest_aler_rule_id_856243_idx',
            old_name='ingest_alertexecution_rule_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='archivedeventbatch',
            new_name='ingest_arch_policy__e379a4_idx',
            old_name='ingest_arch_policy_archived_idx',
        ),
        migrations.RenameIndex(
            model_name='archivedeventbatch',
            new_name='ingest_arch_status_5f2a35_idx',
            old_name='ingest_arch_status_idx',
        ),
        migrations.RenameIndex(
            model_name='eventdeduplicationlog',
            new_name='ingest_even_contrac_9e3dea_idx',
            old_name='ingest_even_contract_idx',
        ),
        migrations.RenameIndex(
            model_name='eventdeduplicationlog',
            new_name='ingest_even_contrac_88aa31_idx',
            old_name='ingest_even_contract_ledger_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='ingest_noti_user_id_1e36bd_idx',
            old_name='ingest_notification_user_read_created_idx',
        ),
        migrations.AddField(
            model_name='trackedcontract',
            name='last_event_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of the last indexed event for this contract', null=True),
        ),
        migrations.AlterField(
            model_name='alertexecution',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contractquota',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
