# Generated by Django 5.2.10 on 2026-03-28 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "ingest",
            "0018_rename_ingest_alertexecution_rule_created_at_idx_ingest_aler_rule_id_856243_idx_and_more",
        ),
        ("ingest", "0023_webhookdeliverylog_payload_bytes"),
    ]

    operations = []
