# Generated by Django 5.2.10 on 2026-04-27 06:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0036_trackedcontract_network"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookdeliverylog",
            name="acknowledged",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True when the subscriber returned the expected acknowledgement header.",
            ),
        ),
        migrations.AddField(
            model_name="webhookdeliverylog",
            name="latency_ms",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Observed delivery latency in milliseconds.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="webhookdeliverylog",
            name="within_sla",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True when acknowledged delivery met the configured SLA target.",
            ),
        ),
        migrations.AddField(
            model_name="webhooksubscription",
            name="ack_header_name",
            field=models.CharField(
                default="X-SoroScan-Ack",
                help_text="HTTP response header that must be present to acknowledge receipt.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="webhooksubscription",
            name="ack_header_value",
            field=models.CharField(
                default="ok",
                help_text="Expected acknowledgement header value.",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="webhooksubscription",
            name="delivery_sla_seconds",
            field=models.PositiveIntegerField(
                default=30,
                help_text="SLA target in seconds for successful delivery acknowledgements.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3600),
                ],
            ),
        ),
        migrations.AddField(
            model_name="webhooksubscription",
            name="escalation_policy",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Ordered escalation policy list, e.g. [{"channel": "slack", "target": "...", "after_failures": 2}]. Defaults to Slack -> SMS -> PagerDuty when empty.',
            ),
        ),
        migrations.CreateModel(
            name="WebhookDeadLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Serialized webhook payload for manual replay/review",
                    ),
                ),
                (
                    "status_code",
                    models.IntegerField(
                        blank=True,
                        help_text="Last observed subscriber HTTP status code",
                        null=True,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                (
                    "retries_exhausted",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="How many attempts were exhausted before dead-lettering",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("resolved", models.BooleanField(db_index=True, default=False)),
                ("resolution_note", models.TextField(blank=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        help_text="Event payload associated with the failed delivery",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_dead_letters",
                        to="ingest.contractevent",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        help_text="Subscription whose delivery failed terminally",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dead_letters",
                        to="ingest.webhooksubscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["subscription", "created_at"],
                        name="ingest_webh_subscri_c66ac3_idx",
                    ),
                    models.Index(
                        fields=["resolved", "created_at"],
                        name="ingest_webh_resolve_76683f_idx",
                    ),
                ],
            },
        ),
    ]
