# Generated by Django 5.2.10 on 2026-04-27 07:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0037_webhookdeadletter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DependencyImpactAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affected_contracts', models.JSONField(blank=True, default=list, help_text='Ordered list of downstream impacted contract IDs.')),
                ('impacted_count', models.PositiveIntegerField(default=0)),
                ('has_cycles', models.BooleanField(default=False)),
                ('risk_score', models.FloatField(default=0.0)),
                ('impact_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=16)),
                ('assessment_details', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_budget_usd', models.DecimalField(decimal_places=2, default=0, help_text='Monthly budget ceiling in USD.', max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('warning_threshold_percent', models.PositiveIntegerField(default=80, help_text='Percent threshold for warning alerts.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('critical_threshold_percent', models.PositiveIntegerField(default=100, help_text='Percent threshold for critical alerts.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)])),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['organization__name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationCostSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Month bucket represented by first day of the month (UTC).')),
                ('rpc_calls', models.PositiveBigIntegerField(default=0)),
                ('storage_bytes', models.PositiveBigIntegerField(default=0)),
                ('compute_units', models.PositiveBigIntegerField(default=0)),
                ('rpc_cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('storage_cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('compute_cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('actual_cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('projected_monthly_cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('breakdown', models.JSONField(blank=True, default=dict, help_text='Cost breakdown by contract, event type, and storage consumption.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-month', 'organization__name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='contractabiversion',
            name='unique_contract_abi_version',
        ),
        migrations.RemoveConstraint(
            model_name='piifield',
            name='unique_pii_contract_event_field',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='ingest_audi_model_n_72ab66_idx',
            old_name='ingest_audi_model_n_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='ingest_audi_user_id_b5fb40_idx',
            old_name='ingest_audi_user_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='contractabiversion',
            new_name='ingest_cont_contrac_bdf59c_idx',
            old_name='ingest_cont_abi_ledger_idx',
        ),
        migrations.RenameIndex(
            model_name='contractdeployment',
            new_name='ingest_cont_contrac_b6b6e1_idx',
            old_name='ingest_cont_deploy_ledger_idx',
        ),
        migrations.RenameIndex(
            model_name='contractdeployment',
            new_name='ingest_cont_bytecod_16d6f3_idx',
            old_name='ingest_cont_bytecode_idx',
        ),
        migrations.RenameIndex(
            model_name='contractsource',
            new_name='ingest_cont_contrac_8cc27b_idx',
            old_name='ingest_cont_contract__a5c2e8_idx',
        ),
        migrations.RenameIndex(
            model_name='datadeletionrequest',
            new_name='ingest_data_status_acd07e_idx',
            old_name='ingest_data_status_idx',
        ),
        migrations.RenameIndex(
            model_name='trackedcontract',
            new_name='ingest_trac_network_9ae130_idx',
            old_name='ingest_trac_network_is_active_idx',
        ),
        migrations.AddField(
            model_name='contractdependency',
            name='risk_score',
            field=models.FloatField(default=0.0, help_text='Edge-level risk score derived from call frequency and graph topology.'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who performed the action (null for system actions)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contractabiversion',
            name='contract',
            field=models.ForeignKey(help_text='Contract this ABI version belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='abi_versions', to='ingest.trackedcontract'),
        ),
        migrations.AlterField(
            model_name='contractabiversion',
            name='deployment',
            field=models.OneToOneField(blank=True, help_text='Deployment that introduced this ABI (null for manually uploaded ABIs)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abi_version', to='ingest.contractdeployment'),
        ),
        migrations.AlterField(
            model_name='contractabiversion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contractdeployment',
            name='contract',
            field=models.ForeignKey(help_text='The tracked contract this deployment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='ingest.trackedcontract'),
        ),
        migrations.AlterField(
            model_name='contractdeployment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contractmetadata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contractsource',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contractverification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='datadeletionrequest',
            name='contracts',
            field=models.ManyToManyField(blank=True, help_text='Contracts whose events should be scrubbed (empty = all contracts)', related_name='deletion_requests', to='ingest.trackedcontract'),
        ),
        migrations.AlterField(
            model_name='datadeletionrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='datadeletionrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, help_text='User who submitted the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='piifield',
            name='contract',
            field=models.ForeignKey(help_text='Contract whose events contain this PII field', on_delete=django.db.models.deletion.CASCADE, related_name='pii_fields', to='ingest.trackedcontract'),
        ),
        migrations.AlterField(
            model_name='piifield',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='contractabiversion',
            unique_together={('contract', 'version_number')},
        ),
        migrations.AlterUniqueTogether(
            name='piifield',
            unique_together={('contract', 'event_type', 'field_path')},
        ),
        migrations.AddField(
            model_name='dependencyimpactassessment',
            name='root_contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_impact', to='ingest.trackedcontract'),
        ),
        migrations.AddField(
            model_name='organizationbudget',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='ingest.organization'),
        ),
        migrations.AddField(
            model_name='organizationcostsnapshot',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_snapshots', to='ingest.organization'),
        ),
        migrations.AddIndex(
            model_name='organizationcostsnapshot',
            index=models.Index(fields=['organization', 'month'], name='ingest_orga_organiz_81c816_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationcostsnapshot',
            unique_together={('organization', 'month')},
        ),
    ]
