# Generated by Django 5.2.10 on 2026-04-28 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0039_trackedcontract_name_createdat_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedcontract',
            name='contract_id',
            field=models.CharField(db_index=True, help_text='Stellar contract address (C...)', max_length=56, unique=True, validators=[django.core.validators.RegexValidator(message="Contract address must start with 'C' and be exactly 56 characters using valid Base32 characters (A-Z, 2-7).", regex='^C[A-Z2-7]{55}$')]),
        ),
    ]
