import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api-reference/soroscan-api",
    },
    {
      type: "category",
      label: "Reference Guides",
      items: [
        {
          type: "doc",
          id: "api-reference/api-reference-guide",
          label: "REST API Guide",
        },
        {
          type: "doc",
          id: "api-reference/graphql",
          label: "GraphQL Reference",
        },
        {
          type: "doc",
          id: "api-reference/playground",
          label: "Interactive Playground",
        },
        {
          type: "doc",
          id: "api-reference/postman",
          label: "Postman Collection",
        },
        {
          type: "doc",
          id: "api-reference/sdk-integration",
          label: "SDK Integration",
        },
        {
          type: "doc",
          id: "api-reference/versioning-deprecation",
          label: "Versioning & Deprecation",
        },
      ],
    },
    {
      type: "category",
      label: "API Endpoints",
      items: [
        {
          type: "doc",
          id: "api-reference/api-analytics-rate-limits-retrieve",
          label: "api_analytics_rate_limits_retrieve",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/api-audit-trail-list",
          label: "api_audit_trail_list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/api-contracts-status-retrieve",
          label: "api_contracts_status_retrieve",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-admin-ingest-errors-retrieve",
          label: "api_ingest_admin_ingest_errors_retrieve",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-admin-organization-costs-retrieve",
          label: "api_ingest_admin_organization_costs_retrieve",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-api-keys-list",
          label: "api_ingest_api_keys_list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-api-keys-create",
          label: "api_ingest_api_keys_create",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-api-keys-retrieve",
          label: "api_ingest_api_keys_retrieve",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-api-keys-destroy",
          label: "api_ingest_api_keys_destroy",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-audit-trail-list",
          label: "api_ingest_audit_trail_list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-compliance-export-retrieve",
          label: "api_ingest_compliance_export_retrieve",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-contracts-list",
          label: "api_ingest_contracts_list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-contracts-create",
          label: "api_ingest_contracts_create",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-contracts-deployments-retrieve",
          label: "api_ingest_contracts_deployments_retrieve",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-contracts-event-types-retrieve",
          label: "api_ingest_contracts_event_types_retrieve",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-contracts-vulnerability-impact-retrieve",
          label: "api_ingest_contracts_vulnerability_impact_retrieve",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-contracts-retrieve",
          label: "api_ingest_contracts_retrieve",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-contracts-update",
          label: "api_ingest_contracts_update",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-contracts-partial-update",
          label: "api_ingest_contracts_partial_update",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-contracts-destroy",
          label: "api_ingest_contracts_destroy",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-contracts-completeness-retrieve",
          label: "api_ingest_contracts_completeness_retrieve",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-contracts-events-list",
          label: "api_ingest_contracts_events_list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-contracts-stats-retrieve",
          label: "api_ingest_contracts_stats_retrieve",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-contracts-upload-source-create",
          label: "api_ingest_contracts_upload_source_create",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-contracts-verify-source-create",
          label: "api_ingest_contracts_verify_source_create",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-contracts-completeness-dashboard-retrieve",
          label: "api_ingest_contracts_completeness_dashboard_retrieve",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-deletion-requests-retrieve",
          label: "api_ingest_deletion_requests_retrieve",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-deletion-requests-create",
          label: "api_ingest_deletion_requests_create",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-events-list",
          label: "api_ingest_events_list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-events-retrieve",
          label: "api_ingest_events_retrieve",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-events-restore-archive-create",
          label: "api_ingest_events_restore_archive_create",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-events-search-list",
          label: "api_ingest_events_search_list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-health-retrieve",
          label: "api_ingest_health_retrieve",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-invocations-list",
          label: "api_ingest_invocations_list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-invocations-retrieve",
          label: "api_ingest_invocations_retrieve",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-record-create",
          label: "api_ingest_record_create",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-teams-list",
          label: "api_ingest_teams_list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-teams-create",
          label: "api_ingest_teams_create",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-teams-retrieve",
          label: "api_ingest_teams_retrieve",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-teams-update",
          label: "api_ingest_teams_update",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-teams-partial-update",
          label: "api_ingest_teams_partial_update",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-teams-destroy",
          label: "api_ingest_teams_destroy",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-teams-members-create",
          label: "api_ingest_teams_members_create",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-transactions-retrieve",
          label: "api_ingest_transactions_retrieve",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-webhooks-list",
          label: "api_ingest_webhooks_list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-webhooks-create",
          label: "api_ingest_webhooks_create",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-webhooks-retrieve",
          label: "api_ingest_webhooks_retrieve",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-webhooks-update",
          label: "api_ingest_webhooks_update",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-webhooks-partial-update",
          label: "api_ingest_webhooks_partial_update",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-webhooks-destroy",
          label: "api_ingest_webhooks_destroy",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-webhooks-dry-run-create",
          label: "api_ingest_webhooks_dry_run_create",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/api-ingest-webhooks-test-create",
          label: "api_ingest_webhooks_test_create",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/api-schema-retrieve",
          label: "api_schema_retrieve",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/api-token-create",
          label: "api_token_create",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/api-token-refresh-create",
          label: "api_token_refresh_create",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "meta",
      items: [
        {
          type: "doc",
          id: "api-reference/api-meta-db-pool-retrieve",
          label: "api_meta_db_pool_retrieve",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "health",
      items: [
        {
          type: "doc",
          id: "api-reference/health-retrieve",
          label: "health_retrieve",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "ready",
      items: [
        {
          type: "doc",
          id: "api-reference/ready-retrieve",
          label: "ready_retrieve",
          className: "api-method get",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
